/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.turno;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.turno.Turno;
import negocvio.abm.turno.ITurno;
import negocvio.abm.turno.TurnoOperacionServicio;

/**
 *
 * @author Alumno
 */
public class JFormCosnultaTurnoOperacion extends javax.swing.JFrame {
    
    DefaultTableModel modelTurnos;

    private ITurno iTurno=new TurnoOperacionServicio();
    private List<Turno> turnos=new ArrayList<Turno>();
    /**
     * Creates new form JFormCosnultaTurno
     */
    public JFormCosnultaTurnoOperacion() {
        initComponents();
        modelTurnos = (DefaultTableModel)jTableCosnultaTurno.getModel();
        cargarModeloTablaTurnos(buscarTurnos(0));
    }
    
    private void cargarModeloTablaTurnos(List<Turno> mTurnos){
        modelTurnos.setNumRows(0);
        for(Turno turno:mTurnos){
            modelTurnos.insertRow(jTableCosnultaTurno.getRowCount(), new Object[]{
                turno.getFecha(),
                turno.getDuenio().getApellido(),
                turno.getDuenio().getNombre(),
                turno.getVeterinario().getNombre(),
                turno.getMascota().getNombre()
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DniVet = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NomVet = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ApeVet = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCosnultaTurno = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        NomDue = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ApeDue = new javax.swing.JTextField();
        DniDue = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        NomMasc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BtnBuscarMascota = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CantGatos = new javax.swing.JTextField();
        CantTruno = new javax.swing.JTextField();
        CantPerros = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dni");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        ApeVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApeVetActionPerformed(evt);
            }
        });

        jTableCosnultaTurno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "CodVet", "Nombre", "Apellido", "CodDue", "Nombre", "Apellido", "Mascota", "TipoMascota", "TipoTurno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableCosnultaTurno);

        jLabel4.setText("Nombre");

        jLabel5.setText("Apellido");

        ApeDue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApeDueActionPerformed(evt);
            }
        });

        jLabel6.setText("Dni");

        jLabel7.setText("Nombre");

        jLabel8.setText("Codigo veterinario");

        jLabel9.setText("Codigo dueño");

        jLabel10.setText("Mascota");

        BtnBuscarMascota.setText("BUSCAR");
        BtnBuscarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarMascotaActionPerformed(evt);
            }
        });

        jLabel11.setText("Cantidad turno:");

        jLabel12.setText("Cantidad perros:");

        jLabel13.setText("Cantidad gatos:");

        CantGatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantGatosActionPerformed(evt);
            }
        });

        CantTruno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantTrunoActionPerformed(evt);
            }
        });

        CantPerros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantPerrosActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel14.setText("Consulta turno operacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CantTruno, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CantPerros, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CantGatos, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DniDue, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NomDue, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ApeDue, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DniVet, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NomVet, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ApeVet, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NomMasc, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnBuscarMascota))
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DniVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(NomVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(ApeVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DniDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(NomDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(ApeDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jLabel10)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomMasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(BtnBuscarMascota))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(CantTruno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(CantGatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CantPerros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        DniVet.getAccessibleContext().setAccessibleName("DniVet");
        NomVet.getAccessibleContext().setAccessibleName("NomVet");
        ApeVet.getAccessibleContext().setAccessibleName("ApeVet");
        NomDue.getAccessibleContext().setAccessibleName("NombDuenio");
        ApeDue.getAccessibleContext().setAccessibleName("ApeDuenio");
        DniDue.getAccessibleContext().setAccessibleName("DniDuenio");
        NomMasc.getAccessibleContext().setAccessibleName("NomMascota");
        NomMasc.getAccessibleContext().setAccessibleDescription("");
        CantGatos.getAccessibleContext().setAccessibleName("TxtCantidadGatos");
        CantTruno.getAccessibleContext().setAccessibleName("TxtCantidadTurno");
        CantPerros.getAccessibleContext().setAccessibleName("TxtCantidadPerros");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ApeVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApeVetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApeVetActionPerformed
    
    private List<Turno>buscarTurnos(int tipoBusquedad){
        if(tipoBusquedad==0){
            return turnos=(List<Turno>)iTurno.buscarTurno(0,"", "");
        }else{
            
           return turnos=(List<Turno>)iTurno.buscarTurno(Integer.parseInt(DniVet.getText().toString()),NomVet.getText().toString(), ApeVet.getText().toString()); 
        }
    }
    private void ApeDueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApeDueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApeDueActionPerformed

    private void BtnBuscarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarMascotaActionPerformed
        
    }//GEN-LAST:event_BtnBuscarMascotaActionPerformed

    private void CantGatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantGatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantGatosActionPerformed

    private void CantTrunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantTrunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantTrunoActionPerformed

    private void CantPerrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantPerrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantPerrosActionPerformed

    /**
     * @param args the command line arguments
     */
   /*
    public static void main(String args[]) {
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFormCosnultaTurnoOperacion().setVisible(true);
            }
        });
    }
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApeDue;
    private javax.swing.JTextField ApeVet;
    private javax.swing.JButton BtnBuscarMascota;
    private javax.swing.JTextField CantGatos;
    private javax.swing.JTextField CantPerros;
    private javax.swing.JTextField CantTruno;
    private javax.swing.JTextField DniDue;
    private javax.swing.JTextField DniVet;
    private javax.swing.JTextField NomDue;
    private javax.swing.JTextField NomMasc;
    private javax.swing.JTextField NomVet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCosnultaTurno;
    // End of variables declaration//GEN-END:variables
}
